import * as CharacterClasses from './definitions';

export const characters: Record<string, any> = {
    "Fairy": CharacterClasses.Fairy,
    "FanShiFu": CharacterClasses.FanShiFu,
    "ShuiLiFang": CharacterClasses.ShuiLiFang,
    "ZongTong": CharacterClasses.ZongTong,
    "ChenGe": CharacterClasses.ChenGe,
    "HaoJing": CharacterClasses.HaoJing,
    "NiuYaoZi": CharacterClasses.NiuYaoZi,
    "DongYin": CharacterClasses.DongYin,
    "FeiNiao": CharacterClasses.FeiNiao,
    "ZhiLang": CharacterClasses.ZhiLang,
    "ZhaoLin": CharacterClasses.ZhaoLin,
    "ZhiYuan": CharacterClasses.ZhiYuan,
    "JiMing": CharacterClasses.JiMing,
    "XuanGe": CharacterClasses.XuanGe,
    "LaoDeng": CharacterClasses.LaoDeng,
    "JiBo": CharacterClasses.JiBo,
    "DongCheDi": CharacterClasses.DongCheDi,
    "Fan": CharacterClasses.Fan,
    "LiXi": CharacterClasses.LiXi,
    "DiaoMin": CharacterClasses.DiaoMin,
    "ZouJieTou": CharacterClasses.ZouJieTou,
    "WuYu": CharacterClasses.WuYu,
    "Song": CharacterClasses.Song,
    "PeiBa": CharacterClasses.PeiBa,
    "ChengXiang": CharacterClasses.ChengXiang,
    "YouDaYu": CharacterClasses.YouDaYu,
    "XiaoQiao": CharacterClasses.XiaoQiao,
    "PaoGe": CharacterClasses.PaoGe,
    "YQJ": CharacterClasses.YQJ,
    "NingNing": CharacterClasses.NingNing,
    "XingXin": CharacterClasses.XingXin,
    "JiGao": CharacterClasses.JiGao,
    "Xian": CharacterClasses.Xian,
    "Jin": CharacterClasses.Jin,
    "WangYuan": CharacterClasses.WangYuan,
    "RenJie": CharacterClasses.RenJie,
    "YanCui": CharacterClasses.YanCui,
    "NiuWenJin": CharacterClasses.NiuWenJin
};
